set nocompatible
set encoding=utf-8
"set lines=40 columns=100 " set font in linux set guifont=Monospace\ 14
" set font in windows
" set guifont=Consolas:h14

" for gvim
" set guioptions-=T  set guioptions-=m  colorscheme murphy " c coding indent, turn off when use python
" set cindent

syntax on
set nu
set autoindent
set cindent
set shiftwidth=4
set tabstop=4
set softtabstop=4
set nobackup
set showcmd
set showmode
set showmatch
filetype on
filetype plugin on 
filetype indent on

" insert # as comment
map <C-I> I# <ESC>

map <silent> <F5> :call Compile()<CR>
function! Compile()
    exec "w"

	if &filetype == "python"
		exec "!python %"
    endif

	if &filetype == "javascript"
		exec "!node %"
	endif 

    if &filetype == 'c'
        exec "!g++ % -o %<"
		exec "!g++ % -o test"
        exec  "!./test"
    elseif &filetype == 'cpp'
        exec "!g++ % -o test"
        exec "!./test"
    elseif &filetype == 'java'
        exec "!javac %"
        exec "!java %<"
    elseif &filetype == 'sh'
        exec "!bash %"
	elseif &filetype == 'php'
		exec "!php -f %"
	endif
endfunc


" Python default settings
" autocmd FileType python set tabstop=4 shiftwidth=4 expandtab ai
autocmd FileType ruby set tabstop=2 shiftwidth=2 softtabstop=2 expandtab ai
autocmd BufRead,BufNew *.md,*.mkd,*.markdown  set filetype=markdown.mkd

" when save python file, then delete redundant space
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

" autocmd FileType c,cpp,java,go,php,javascript,puppet,python,rust,twig,xml,yml,perl autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()


" automate insert the header of file
"autocmd BufNewFile *.sh,*.py exec :call AutoSetFileHead()
"map <silent> <C-M> :call AutoSetFileHead()<CR>
"autocmd BufNewFile *.sh,*.py call AutoSetFileHead()
function! AutoSetFileHead()
    if &filetype == 'sh'
        call setline(1, "\#!/bin/bash")
    endif
    if &filetype == 'python'
        call setline(1, "\#!/usr/bin/env python")
        call append(1, "\# encoding: utf-8")
    endif
    normal G
    normal o
    normal o
endfunc

" when vimrc changed, thend auto load  with windows
"autocmd! bufwritepost _vimrc source %
" when vimrc changed, thend auto load  with linux
autocmd! bufwritepost .vimrc source %

"when vim exit, cat file content in terminal
"set t_ti = t_te=

" history account
set history=2000

let mapleader=","
" let g:syntastic_quiet_warnings=1
" let g:syntastic_quiet_messages = {'level': 'error'}
" let g:syntastic_python_checker_args = '--ignore=E225'
autocmd FileType python set expandtab
